export const ALL_HEROES_REQUEST = 'ALL_HEROES_REQUEST';
export const ALL_HEROES_SUCCESS = 'ALL_HEROES_SUCCESS';
export const ALL_HEROES_FAILURE = 'ALL_HEROES_FAILURE';

// Saga handles this actionType
export const ALL_HEROES_FETCHED = 'ALL_HEROES_FETCHED';
